-- MySQL Script generated by MySQL Workbench
-- Sat Sep 29 19:54:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id7158914_proyinf4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id7158914_proyinf4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id7158914_proyinf4` DEFAULT CHARACTER SET utf8 ;
USE `id7158914_proyinf4` ;

-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`deportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`deportes` (
  `deporteid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`deporteid`),
  UNIQUE INDEX `deporteid_UNIQUE` (`deporteid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`divisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`divisiones` (
  `divisionid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `deporteid` INT UNSIGNED NULL,
  `nombre` VARCHAR(200) NULL,
  PRIMARY KEY (`divisionid`),
  INDEX `deporteid_idx` (`deporteid` ASC),
  CONSTRAINT `deporteid`
    FOREIGN KEY (`deporteid`)
    REFERENCES `id7158914_proyinf4`.`deportes` (`deporteid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`equipos` (
  `equipoid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `divisionid` INT UNSIGNED NULL,
  `nombre` VARCHAR(100) NULL,
  `carrera` VARCHAR(120) NULL,
  `facultad` VARCHAR(120) NULL,
  PRIMARY KEY (`equipoid`),
  UNIQUE INDEX `equipoid_UNIQUE` (`equipoid` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  CONSTRAINT `divisionid`
    FOREIGN KEY (`divisionid`)
    REFERENCES `id7158914_proyinf4`.`divisiones` (`divisionid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`jugadores` (
  `jugadorid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipoid` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(160) NULL,
  `edad` INT NULL,
  `ano_ingreso` INT NULL,
  UNIQUE INDEX `jugadorid_UNIQUE` (`jugadorid` ASC),
  PRIMARY KEY (`jugadorid`, `equipoid`),
  INDEX `equipoid_idx` (`equipoid` ASC),
  CONSTRAINT `equipoid`
    FOREIGN KEY (`equipoid`)
    REFERENCES `id7158914_proyinf4`.`equipos` (`equipoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`lugares` (
  `lugarid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NULL,
  `ubicacion` VARCHAR(120) NULL,
  `capacidad` VARCHAR(45) NULL,
  PRIMARY KEY (`lugarid`),
  UNIQUE INDEX `lugarid_UNIQUE` (`lugarid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`partidos` (
  `partidoid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipo_1` INT UNSIGNED NULL,
  `equipo_2` INT UNSIGNED NULL,
  `divisionid` INT UNSIGNED NULL,
  `lugarid` INT UNSIGNED NULL,
  `ganador` INT UNSIGNED NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(45) NULL,
  PRIMARY KEY (`partidoid`),
  UNIQUE INDEX `partidoid_UNIQUE` (`partidoid` ASC),
  INDEX `lugar_idx` (`lugarid` ASC),
  INDEX `ganador_idx` (`ganador` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  INDEX `equipo1_idx` (`equipo_1` ASC),
  INDEX `equipo2_idx` (`equipo_2` ASC),
  CONSTRAINT `lugarid`
    FOREIGN KEY (`lugarid`)
    REFERENCES `id7158914_proyinf4`.`lugares` (`lugarid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ganador`
    FOREIGN KEY (`ganador`)
    REFERENCES `id7158914_proyinf4`.`equipos` (`equipoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `divisionid1`
    FOREIGN KEY (`divisionid`)
    REFERENCES `id7158914_proyinf4`.`divisiones` (`divisionid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipo1`
    FOREIGN KEY (`equipo_1`)
    REFERENCES `id7158914_proyinf4`.`equipos` (`equipoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipo2`
    FOREIGN KEY (`equipo_2`)
    REFERENCES `id7158914_proyinf4`.`equipos` (`equipoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`campeonatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`campeonatos` (
  `campeonatoid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `divisionid` INT UNSIGNED NULL,
  `ano` INT NULL,
  `nombre` VARCHAR(120) NULL,
  `semestre` VARCHAR(45) NULL,
  `campeon` INT UNSIGNED NULL,
  `fecha_inicio` DATE NULL,
  `fecha_termino` DATE NULL,
  `reglamento` VARCHAR(120) NULL,
  UNIQUE INDEX `ligaid_UNIQUE` (`campeonatoid` ASC),
  PRIMARY KEY (`campeonatoid`),
  INDEX `campeon_idx` (`campeon` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  CONSTRAINT `campeon`
    FOREIGN KEY (`campeon`)
    REFERENCES `id7158914_proyinf4`.`equipos` (`equipoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `divisionid2`
    FOREIGN KEY (`divisionid`)
    REFERENCES `id7158914_proyinf4`.`divisiones` (`divisionid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`arbitros` (
  `arbitroid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `fecha_ingreso` DATE NULL,
  PRIMARY KEY (`arbitroid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`arbitrajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`arbitrajes` (
  `partidoid` INT UNSIGNED NOT NULL,
  `arbitroid` INT UNSIGNED NOT NULL,
  `tipo` VARCHAR(80) NULL,
  PRIMARY KEY (`arbitroid`, `partidoid`),
  INDEX `partidoid_idx` (`partidoid` ASC),
  CONSTRAINT `partidoid`
    FOREIGN KEY (`partidoid`)
    REFERENCES `id7158914_proyinf4`.`partidos` (`partidoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `arbitroid`
    FOREIGN KEY (`arbitroid`)
    REFERENCES `id7158914_proyinf4`.`arbitros` (`arbitroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`usuarios` (
  `usuarioid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `correo` VARCHAR(200) NULL,
  `password` VARCHAR(200) NULL,
  `admin` TINYINT NULL,
  PRIMARY KEY (`usuarioid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`sanciones` (
  `sancionid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jugadorid` INT UNSIGNED NOT NULL,
  `tiempo` VARCHAR(45) NULL,
  `comentario` VARCHAR(200) NULL,
  INDEX `jugadorid_idx` (`jugadorid` ASC),
  PRIMARY KEY (`sancionid`, `jugadorid`),
  CONSTRAINT `jugadorid0`
    FOREIGN KEY (`jugadorid`)
    REFERENCES `id7158914_proyinf4`.`jugadores` (`jugadorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id7158914_proyinf4`.`partido_jugadors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id7158914_proyinf4`.`partido_jugadors` (
  `partidoid` INT UNSIGNED NOT NULL,
  `jugadorid` INT UNSIGNED NOT NULL,
  `puntos` INT NULL DEFAULT 0,
  `triples` INT NULL DEFAULT 0,
  `amarilla` TINYINT NULL DEFAULT 0,
  `roja` TINYINT NULL DEFAULT 0,
  `faltas_b` INT NULL DEFAULT 0 COMMENT 'faltas basquetball',
  PRIMARY KEY (`partidoid`, `jugadorid`),
  INDEX `jugadorid_idx` (`jugadorid` ASC),
  CONSTRAINT `partidoid0`
    FOREIGN KEY (`partidoid`)
    REFERENCES `id7158914_proyinf4`.`partidos` (`partidoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `jugadorid1`
    FOREIGN KEY (`jugadorid`)
    REFERENCES `id7158914_proyinf4`.`jugadores` (`jugadorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
